version: '3.8'

volumes:
  pg_data:
  django_static:
  react_static:
  media_value:

services:
  db:
    image: postgres:15-alpine
    container_name: foodgram-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: igorpanda/foodgram_backend:latest
    container_name: foodgram-backend
    restart: always
    volumes:
      - django_static:/backend_static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: igorpanda/foodgram_frontend:latest
    container_name: foodgram-front
    env_file:
      - .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - react_static:/frontend_static/

  nginx:
    image: igorpanda/foodgram_gateway:latest
    container_name: foodgram-proxy
    ports:
      - "8000:80"
    volumes:
      - django_static:/django_static/
      - react_static:/react_static/ 
      - media_value:/app/media/
    depends_on:
      - backend
      - frontend