"""Константы для ограничения длины полей в моделях приложения recipes."""

TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32

RECIPE_NAME_MAX_LENGTH = 256
RECIPE_MIN_COOKING_TIME = 1

INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_UNIT_MAX_LENGTH = 64
INGREDIENT_MIN_AMOUNT = 1

MAX_SMALL_INTEGER_VALUE = 32767
